let menu = [
  {
    title: "Интро",
    url: "index",
    sections: [
      { title: "Что вы будете делать?", url: "what-do" },
      { title: "Коротко об игре", url: "nutshell" },
      { title: "Инструменты игры", url: "tools" },
      { title: "Третий Горизонт", url: "horizon" },
    ],
  },
  {
    title: "PC",
    url: "chars",
    sections: [
      {
        title: "Команда",
        url: "crew",
        section: [
          { title: "Вольные торговцы", url: "free_traders" },
          { title: "Наемники", url: "mercenaries" },
          { title: "Исследователи", url: "explorers" },
          { title: "Агенты", url: "agents" },
          { title: "Пилигримы", url: "piligrims" },
        ],
      },
      {
        title: "Персонажи",
        url: "pc",
        sections: [
          { title: "Артист", url: "artist" },
          { title: "Сетевой паук", url: "data_spider" },
          { title: "Беглец", url: "fugitive" },
          { title: "Негоциант", url: "negotiator" },
          { title: "Оперативник", url: "operative" },
          { title: "Пилот", url: "pilot" },
          { title: "Проповедник", url: "preacher" },
          { title: "Ученый", url: "scientist" },
          { title: "Матрос", url: "ship_worker" },
          { title: "Солдат", url: "soldier" },
          { title: "Первопроходец", url: "trailblazer" },
        ],
      },
    ],
  },
  {
    title: "Навыки",
    url: "skills",
    sections: [
      { title: "Общие", url: "general" },
      { title: "Специальные", url: "advanced" },
    ],
  },
  {
    title: "Таланты",
    url: "talents",
    sections: [
      { title: "Команды", url: "group" },
      { title: "Ликов", url: "icon" },
      { title: "Личные", url: "general" },
      { title: "Стигмы пасынков", url: "humanite" },
      { title: "Кибернетические Импланты", url: "cybernetic" },
      { title: "Бионические Модификации", url: "bionic" },
      { title: "Мистические Практики", url: "mystical" },
    ],
  },
  {
    title: "Сражения",
    url: "combat",
  },
  {
    title: "Снаряжение",
    url: "equipment",
    sections: [
      { title: "Снаряжение", url: "gear" },
      { title: "Оружие и броня", url: "weapon_armor" },
      { title: "Импланты и модификации", url: "mods" },
    ],
  },
  {
    title: "Космос",
    url: "space",
    sections: [
      { title: "Корабли", url: "spacecraft" },
      { title: "Создание корабля", url: "your_ship" },
      { title: "Сражения", url: "combat" },
    ],
  },
  {
    title: "Горизонт",
    url: "third_horizon",
    sections: [
      { title: "История", url: "history" },
      { title: "Новая Эра", url: "new_era" },
      { title: "Горизонт сегодня", url: "today" },
    ],
  },
  {
    title: "Фракции",
    url: "faction",
    sections: [
      { title: "Консорциум", url: "consortium" },
      { title: "Вольная лига", url: "free_league" },
      { title: "Легион", url: "legion" },
      { title: "Синдикат", url: "syndicate" },
      { title: "Зенитийская гегемония", url: "zenithian_hegemony" },
      { title: "Дракониты", url: "draconites" },
      { title: "Церковь Ликов", url: "church_of_the_icons" },
      { title: "Храм Алама", url: "ahlams_temple" },
      { title: "Орден Изгоев (неприкасаемых)", url: "order_of_the_pariah" },
      { title: "Федерация кочевников", url: "nomad_federation" },
      { title: "Младшая лига", url: "small_players" },
    ],
  },
  {
    title: "Жители",
    url: "people",
    sections: [
      { title: "Повседневная жизнь", url: "daily_life" },
      { title: "Технологии", url: "technology" },
      { title: "Культура", url: "culture" },
      { title: "Девять Ликов", url: "icon_belief" },
      { title: "Церковь Ликов", url: "church" },
      { title: "Народные верования", url: "faith" },
      { title: "Предания и мифы", url: "spirits" },
    ],
  },
  {
    title: "Лор",
    url: "lore",
    sections: [
      {
        title: "Кориолис",
        url: "coriolis",
        sections: [
          { title: "Кольцо", url: "ring" },
          { title: "Ядро", url: "core" },
          { title: "Шпиль", url: "spire" },
          { title: "Подвал", url: "cellar" },
          { title: '"Невод"', url: "net" },
          { title: "Правительство", url: "government" },
          { title: "Факты", url: "facts" },
        ],
      },
      {
        title: "Куа",
        url: "kua_system",
        sections: [
          { title: "Лубау", url: "lubau" },
          { title: "Хина", url: "jina" },
          { title: "Куа", url: "kua" },
          { title: "Зин", url: "xene" },
          { title: "Сарха", url: "surha" },
          { title: "Пограничье", url: "rimward_reach" },
        ],
      },
      {
        title: "Атлас",
        url: "atlas",
        sections: [
          { title: "Астрография", url: "astrography" },
          { title: "Торговые пути", url: "routes" },
          { title: "Алголь", url: "algol" },
          { title: "Мира", url: "mira" },
          { title: "Дабаран", url: "dabaran" },
          { title: "Садааль", url: "sadaal" },
          { title: "Залос", url: "zalos" },
          { title: "Одакон", url: "odacon" },
          { title: "Опорный квадрант", url: "quadrant_of_the_pillar" },
          { title: "Жемчужины", url: "small_gems" },
        ],
      },
      {
        title: "Чудовища и Джинны",
        url: "beasts",
        sections: [
          { title: "Зверолюди", url: "semi_intelligence" },
          { title: "Звери", url: "beasts" },
          { title: "Криптоморфы", url: "darkmorphs" },
          { title: "Машины", url: "constructs" },
          { title: "Духи и саркофагои", url: "spirits_sarcofagoi" },
          { title: "Болезни и психомемы", url: "diseases_mems" },
        ],
      },
      {
        title: "Принципы игры",
        url: "campaign",
        sections: [
          { title: "", url: "" },
          { title: "", url: "" },
        ],
      },
    ],
  },
];
